# Site
repository: Senpu2693/Senpu2693.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Bharatraj Elavarasan
title: Computer Engineering Major
email: elavara1@msu.edu
# website: Pending

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  Senpu2693
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: bharatraj-elavarasan-814655286
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: "@bharatelav"
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
  # icon: fas fa-globe
  # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Bharatraj, and I'm a computer engineering major at Michigan State University. I'm a member of MSU's Formula SAE team, where I apply my skills in circuit design and system integration. Alongside hardware projects, I also have experience in basic web development.

  I am most skilled in: <mark>Electrical design and harness engineering</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Nrshmnt.ai
        link: https://devpost.com/software/nrshmnt-ai
        # link_text: Project Website
        additional_links:
          - title:  Senpu2693/Nrshmnt-public
            icon: fab fa-github
            url: https://github.com/Senpu2693/Nrshmnt-public
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A recipe generator that creates balanced meals tailored to your exact protein, fat, and carbohydrate needs.
        description: | # this will include new lines to allow paragraphs
          I built this website to simplify the process of cooking while tracking macros, which can often be time-consuming and tedious. By entering your target calories, protein, and food preferences, the app uses the <mark>ChatGPT 3.5 API</mark> to generate seven recipes in parallel and selects the one that best matches your input—removing the hassle of calculating portions and finding ingredients so you can get straight to cooking.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Michigan State Formula SAE
        link: https://www.msuformularacing.com/
        # link_text: boringcompany.com
        sub_title: LV Power Lead
        caption: October 2024 - Present
        quote: >
          Designing and testing custom electronics and wiring harnesses for high-voltage systems in an open-wheel electric race car.
        description: | # this will include new lines to allow paragraphs
            As the LV Power Lead, I focused on <mark>wiring harness design</mark> in RapidHarness and hands-on harness manufacturing, ensuring reliable integration across vehicle systems. In addition, I worked on <mark>PCB design</mark> using Altium, developed circuit models for various subsystems, and built load bank models to support accumulator testing. My role encompassed the design, modeling, and validation of both low- and high-voltage electrical components critical to vehicle performance and safety.

      - layout: left
        title: Michigan State Rocketry
        link: https://msurocketry.org/
        # link_text: boringcompany.com
        sub_title: Electrical System Member - XBee remote communications
        caption: September 2024 - June 2025
        quote: >
          Integrating embedded systems and RF communication to support telemetry and ground-station interfacing.
        description: | # this will include new lines to allow paragraphs
            Developed a telemetry system using XBee modules to wirelessly transmit flight data from the rocket to a ground station. Used <mark>minicom</mark> on a Raspberry Pi to remotely interface with the ground-side XBee, enabling real-time data reception and monitoring during launch operations.


      - layout: left
        title: iCode Novi
        link: https://icodeschool.com/
        # link_text: boringcompany.com
        sub_title: Assistant Director
        caption: June 2023 - September 2024
        quote: >
          Empowering the next generation through hands-on tech education and leadership in STEM learning environments.
        description: | # this will include new lines to allow paragraphs
            Guided instructors at the top-performing iCode franchise nationwide, supported course and camp sales, developed teaching frameworks, and assisted with promotional materials. Taught over 100 students and collaborated with dozens of instructors across various subjects, including game development with Unreal Engine 5 and Roblox Studio, robotics with VEX IQ, and web development using CSS, HTML, JavaScript, and PHP. Represented iCode at conventions such as ASEICON and <mark>optimized curriculum</mark> delivery for in-house technology.

      
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Michigan State University
        caption: "2023 - Present · GPA: 4.0"
        sub_title: Bachelor of Science, Computer Engineering
        quote: >
          Founded in 1855, Michigan State University is a top-tier public research university recognized for its excellence in engineering, innovation, and interdisciplinary learning.
        description: | # this will include new lines to allow paragraphs
          As a Computer Engineering student at Michigan State University, I’ve built a strong foundation in both <mark>hardware</mark> and <mark>software systems</mark> through coursework in Circuits and Systems I & II, Electric Circuits Laboratory, and Introduction to Programming II (CSE232). I’ve applied these skills through hands-on involvement in the Formula SAE and Rocketry teams, contributing to real-world electronics, PCB design, and embedded telemetry systems.

  - title: Beyond Engineering
    layout: text
    content: | # this will include new lines to allow paragraphs
      Beyond my focus on hardware systems and embedded development, I also enjoy:
      - Running
      - Learning Japanese
      - Cooking
      - [Animation](https://www.youtube.com/watch?v=nhA_BdsXX9k)

    # Look at this cool image  (tab once)
    # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees") (tab once)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
