# Site
repository: Senpu2693/Senpu2693.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Bharatraj Elavarasan
title: Computer Engineering & Applied Mathematics
email: elavara1@msu.edu
# website: Pending

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  Senpu2693
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: bharatraj-elavarasan-814655286
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: "@bharatelav"
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
  # icon: fas fa-globe
  # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Bharatraj. I’m a Computer Engineering and Applied Mathematics student at MSU with a 4.0 GPA, currently serving as the Low Voltage Power Lead for our Formula SAE team. My recent work includes leading the electrical architecture for a formula-style vehicle, where I manage crucial power and communication signals. Beyond the Shop, I’ve developed motor control logic using computer vision, a project that recently took runner up at spartahack, and I’m currently studying graduate-level optimization to apply more rigorous decision-making frameworks to complex system integrations.

  I am most skilled in: <mark>Systems and Controls</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Auto Spot
        link: https://devpost.com/software/otto-spot 
        # link_text: Project Website
        additional_links:
          - title:  Auto Spot Github
            icon: fab fa-github
            url: https://github.com/yourlocaljosh/auto-spot
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Using computer vision algorithms connected to a microcontroller that power a motor, you can solo lift in safety, without danger.
        description: | # this will include new lines to allow paragraphs
         I architected the control system using a Teensy 4.1 and an L298 logic controller to drive a high-torque worm gear assembly. By optimizing the mechanical advantage and current draw of a standard 12V DC motor, I successfully built a prototype capable of a 150 lb vertical lift. The project proved that high-stakes safety mechanisms don't require industrial-level budgets; our total build cost was under $70, showcasing a path for scalable, affordable safety integration.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Michigan State Formula SAE
        link: https://www.msuformularacing.com/
        # link_text: boringcompany.com
        sub_title: LV Power Lead
        caption: October 2024 - Present
        quote: >
          Designing and testing custom electronics and wiring harnesses for high-voltage systems in an open-wheel electric race car.
        description: | # this will include new lines to allow paragraphs
            As the LV Power Lead, I focused on wiring harness design in RapidHarness and hands-on harness manufacturing, ensuring reliable integration across vehicle systems. In addition, I worked on PCB design using Altium, developed circuit models for various subsystems, and built load bank models to support accumulator testing. My role encompassed the design, modeling, and validation of both low- and high-voltage electrical components critical to vehicle performance and safety.

      - layout: left
        title: Michigan State Rocketry
        link: https://msurocketry.org/
        # link_text: boringcompany.com
        sub_title: Electrical System Member - XBee remote communications
        caption: September 2024 - June 2025
        quote: >
          Integrating embedded systems and RF communication to support telemetry and ground-station interfacing.
        description: | # this will include new lines to allow paragraphs
            Developed a telemetry system using XBee modules to wirelessly transmit flight data from the rocket to a ground station. Used minicom on a Raspberry Pi to remotely interface with the ground-side XBee, enabling real-time data reception and monitoring during launch operations.


      - layout: left
        title: iCode Novi
        link: https://icodeschool.com/
        # link_text: boringcompany.com
        sub_title: Assistant Director
        caption: June 2023 - September 2024
        quote: >
          Empowering the next generation through hands-on tech education and leadership in STEM learning environments.
        description: | # this will include new lines to allow paragraphs
            Guided instructors at the top-performing iCode franchise nationwide, supported course and camp sales, developed teaching frameworks, and assisted with promotional materials. Taught over 100 students and collaborated with dozens of instructors across various subjects, including game development with Unreal Engine 5 and Roblox Studio, robotics with VEX IQ, and web development using CSS, HTML, JavaScript, and PHP. Represented iCode at conventions such as ASEICON and optimized curriculum delivery for in-house technology.

      
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Michigan State University
        caption: "2023 - Present · GPA: 4.0"
        sub_title: Bachelor of Science, Computer Engineering
        quote: >
          Founded in 1855, Michigan State University is a top-tier public research university recognized for its excellence in engineering, innovation, and interdisciplinary learning.
        description: | # this will include new lines to allow paragraphs
          Currently engaged in graduate-level study of Multi-Criterion Optimization to solve complex, industry-level engineering problems. I am also a ULA for ECE202: Circuits and Systems II where I teach AC circuit analysis and circuit system design.

  - title: Beyond Engineering
    layout: text
    content: | # this will include new lines to allow paragraphs
      Beyond my focus on hardware systems and embedded development, I also enjoy:
      - Running
      - Learning Japanese
      - Cooking

    # Look at this cool image  (tab once)
    # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees") (tab once)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
